### ISSUE TITLE
Compatibility beta 11.0

### ISSUE THREAD

**Issue by Asaelle** [kemayo/wow-questschanged#3]
Hello, thank you for your work on this useful addon.

I would like to use it to start tracking quests for the community, but currently, the addon doesn't seem to load when I type commands. The game doesn't recognize them, such as "/questschanged icon" etc.

The only error I have is:

Interface/AddOns/QuestsChanged/addon.lua:2: attempt to call global 'GetAddOnMetadata' (a nil value)

but it seems completely unrelated.

Thanks for your help.

**Comment by kemayo** [comment]
Betas turn off all the deprecation-wrappers that otherwise exist in release versions of WoW (e.g. GetAddOnMetadata was moved to C_AddOns.GetAddOnMetadata in 10.2.6 I think), which is what's breaking here.

You can do this in-game to make it work again: `/console loadDeprecationFallbacks 1`

I'll probably get at least an alpha out with it working without needing the fallbacks turned on, but I'm not rushing to get that done.
